config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'messages#index'
  resources :users, only: [:edit, :update]
  resources :groups, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,  :validatable

  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
= form_with model: @group, local: true do |f|
  = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
  = f.collection_check_boxes :user_ids, User.all, :id, :name
  = f.submit "Save", class: "SettingGroupForm__button"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
＜チャット画面＞

app/views/messages/_side_bar.html.haml
.SideBar
  .LeftHeader
    .LeftHeader__list
      %h3.LeftHeader__userName
        = current_user.name
      %ul.LeftHeader__iconList
        %li.LeftHeader__Icon
          = link_to new_group_path do
            = icon('fas', 'edit')
        %li.LeftHeader__Icon
          = link_to edit_user_path(current_user) do
            = icon('fas', 'cog')
  .GroupList
    - current_user.groups.each do |group|
      .Group
        = link_to '#' do
          .Group__name
            = group.name
          .Group__message
            メッセージはまだありません

app/views/messages/index.html.haml
.wrapper

  = render 'side_bar'

  .chat
    .header
      .left-header
        .left-header__title
          グループ名
        %ul.left-header__members
          Member：
          %li.member
            メンバー名
          %li.member
            メンバー名
          %li.member
            メンバー名
      .right-header
        .right-header__button
          Edit
    .messages
      .message
        .upper-message
          .upper-message__user-name
            メンバー
          .upper-message__date
            2017/04/04
        .lower-meesage
          .lower-message__content
            メッセージ
      .message
        .upper-message
          .upper-message__user-name
            メンバー
          .upper-message__date
            2017/04/04
        .lower-meesage
          .lower-message__content
            メッセージ
      .message
        .upper-message
          .upper-message__user-name
            メンバー
          .upper-message__date
            2017/04/04
        .lower-meesage
          .lower-message__content
            メッセージ
    .form
      %form
        %input.form__message
        .form__mask
          %label.form__mask__image
            = icon('fa','image',class: 'icon')
            %input.hidden{type: 'file'}
        %input.form__submit{type: 'submit', value: 'Send'}

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'